import Head from 'next/head';

export default function Home(props) {
  const random = props.random;
  return (
    <div>
      <Head>
        <title>Create Next App Leon Emma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-wheat/20 h-full w-full">
        <h2>Hello</h2>
      </div>
    </div>


  )
}


import getDatabase from '../lib/database';
export const getServerSideProps = async (context)=>{
  const db = await getDatabase();
  const collection = db.collection("words");
  const _random = collection.aggregate([{$sample: {size: 1}}])
  const _words = collection.find({}, {sort: {_id: -1}, limit: 10})
  const random = await _random.toArray();
  const words = await _words.toArray();
  return {
    props:{
      random: JSON.parse(JSON.stringify(random[0])),
      words: JSON.parse(JSON.stringify(words))
    }
  };
}
